version: '3'
services:

  gateway-server:
    image: semihshn/freetaxi:gateway-server
    container_name: gateway-server-container
    ports:
      - '5555:5555'
    environment:
      - SECURE_KEY_USERNAME=randomSecureKeyUsername!
      - SECURE_KEY_PASSWORD=randomSecureKeyPassword!
      - PASSENGER_SERVICE_URL=passenger-service:4444
      - DRIVER_SERVICE_URL=driver-service:3333
      - DATABASE_URL=jdbc:h2:mem:db_gateway
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
      - JWT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKUXKxF3hJrntm3+BAWnjD5vup4DUHqmg9ewXbkTxHufpxcpjFTUOTPg9j30kT4L1pNHp3HbrJ5mu15MjiOgSvIBNrjieVTOID1X1mo7EsFwg4Gs4bgX3+MtUxNueSZ9qCgiWI+Q5c71S9ZqFE4VfUKsXphnzGMI49fZRSpv10irsBaOSDJ+iLroNJoH3SdvzJC0hjTUatlpVENv/36sRKm3E1xIph9zjSsoawaLSzpw1kl9ZJ76OQ9l3LdkGG58qhNICnFrguR0zAhT/eWvd6y5s1sDwl8FMQ0PbC0xZuIHwX9Cs6NyPaEffPQdFcqRSDh/6NMC0EbYoT3UFB7VRQIDAQAB
      - JWT_PRIVATE_KEY=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCYpRcrEXeEmue2bf4EBaeMPm+6ngNQeqaD17BduRPEe5+nFymMVNQ5M+D2PfSRPgvWk0encdusnma7XkyOI6BK8gE2uOJ5VM4gPVfWajsSwXCDgazhuBff4y1TE255Jn2oKCJYj5DlzvVL1moUThV9QqxemGfMYwjj19lFKm/XSKuwFo5IMn6Iuug0mgfdJ2/MkLSGNNRq2WlUQ2//fqxEqbcTXEimH3ONKyhrBotLOnDWSX1knvo5D2Xct2QYbnyqE0gKcWuC5HTMCFP95a93rLmzWwPCXwUxDQ9sLTFm4gfBf0Kzo3I9oR989B0VypFIOH/o0wLQRtihPdQUHtVFAgMBAAECggEAagu3jsoxuERN2iWMJYswHXR69rE0KEMtT8cW1eXwX75q6hBjYwTD84GhNjFQqV7rpoTncOLe9IuPX3hhwxXpFGgQg83qONS75xX24hUnOR5+Zj4+twnIPFh9cou7YhtljN9lDRWgWqdvLuKlC7o7n6wkSAulgQ8EbBXW8gBLdsoJAR9SZqDHMvGe95Pm4/s3SUqsFRw0cbufIBJ4XcLq9JKkecidbxihYfFvEZNIGN2GDc3x/w7SOL+EbrJcH40Aj/VKBzGChWONJaWlbq1bwBZZc93WcwYa8Zz0T3caMEELo9NW2KAUqq3tGxreQfZzcqeBrGL3VoeZUYgZxgEUeQKBgQDLzA0HIq7lTu1HrqZR3E3MaZMPBB76OXL5ndiQRCwDjv4ZGTArvxE2wASw2VxcNHq4GF+I2hdJlMkqG77ZiLExFm8kRLTRmRf1zIt9ISleQ74hpecAW06PxF//Qj0pxzxkXajoeigM29NW11G6UBmZ4ylbxTwZXzz0STWw9Fef9wKBgQC/vr7wt88oKrI2H9nJru1jn29IvEF/eisXBbjKV4CJM/3QiKrDIfg0iGcn4P+mes/gQwCdnsz/wUntLnNyuM0SYKfZzEL5Kt0onaj4nnF6I5Sq6OYKCFG6Dm3xiljfOQbDyGva+Pk8OylbERKHIo0enL2cVGnDb2cd2340szMdowKBgC8WGDR72Pj2QXB8c8UaJ4eBJQ8lHpslxuDRjYXXmmvAEAlwfma9IJcLyompzuMm5OvABeKysQq5K7lk67WLFZWH32n7zeNXgeeyuM/SZ6J1+GoB0NuOPRqOfreVcFhExjlSQoJkJvjBmZTI7wMjGqcpixa+/WHHVWgDujoGWnCFAoGARiUapucnQpN0BHbcbnqu314JEPvFnkPsFY0DUAp4vDin5qzIg4Ae0+D+k8ks3RNajrkUNZVNe1aTm8/9bf+LDekMHpIqAgsbQuuCUAlui/cOQQPYe90VQNJciBtLbcXn4qGkS0P/sXgXJfh15bfPFl7Swqji1BsiBvswDUltLq8CgYEAsV7+sSszLSU/y3CCGyAs9ECshfmYFctoReRN2JQ0OEL5bFMwAg/Ysiwvf/TBZl5aE6GGtuSe0nIrlcD0+DvBqzW6UmHV9XHsX/qiLNPU/BvNPiwjS9W/Je9w8nlildXRQpaS0tJu4CTmIpI6OpWTCEv79YcUIQ/0rQpNHPheBx8=
    networks:
      - microservicesNetwork

  driver-service:
    image: semihshn/freetaxi:driver-service
    container_name: driver-service-container
    ports:
      - '3333:3333'
    environment:
      - NOTIFICATION_SERVICE_URL=notification-service:8888
      - PAYMENT_SERVICE_URL=payment-service:7777
      - SECURE_KEY_USERNAME=randomSecureKeyUsername!
      - SECURE_KEY_PASSWORD=randomSecureKeyPassword!
    networks:
      - microservicesNetwork

  passenger-service:
    image: semihshn/freetaxi:passenger-service
    container_name: passenger-service-container
    ports:
      - '4444:4444'
    environment:
      - PAYMENT_SERVICE_URL=payment-service:7777
      - SECURE_KEY_USERNAME=randomSecureKeyUsername!
      - SECURE_KEY_PASSWORD=randomSecureKeyPassword!
    networks:
      - microservicesNetwork

  notification-service:
    image: semihshn/freetaxi:notification-service
    container_name: notification-service-container
    ports:
      - '8888:8888'
    environment:
      - SECURE_KEY_USERNAME=randomSecureKeyUsername!
      - SECURE_KEY_PASSWORD=randomSecureKeyPassword!
    networks:
      - microservicesNetwork

  payment-service:
    image: semihshn/freetaxi:payment-service
    container_name: payment-service-container
    ports:
      - '7777:7777'
    environment:
      - SECURE_KEY_USERNAME=randomSecureKeyUsername!
      - SECURE_KEY_PASSWORD=randomSecureKeyPassword!
    networks:
      - microservicesNetwork

networks:
  microservicesNetwork: